---
  - name: update repositories cache and install NFS in RedHat systems
    yum: name=nfs-utils

  - set_fact: NFS_SERVICE="nfs"

  - set_fact: NFS_SERVICE="nfs-server"
    when: ansible_distribution_major_version >= "7"
 
  - name: Ensure rpcbind is stopped
    systemd:
      name: rpcbind
      enabled: no
      masked: yes

  - name: Ensure rpcbind.socket is stopped
    systemd:
      name: rpcbind.socket
      enabled: no
      masked: yes

  - name: NFS configure RH8
    ini_file:
      path: /etc/nfs.conf
      section: "{{item.section}}"
      option: "{{item.option}}"
      value: "{{item.value}}"
    with_items:
    - {'section': 'nfsd', 'option': 'vers3', 'value': 'no'}
    notify:
     - restart nfs
    when: ansible_distribution_major_version >=  "8"
    register: nfs_config8

  - name: NFS configure RH7
    lineinfile:
      dest: /etc/sysconfig/nfs
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
      state: present
      create: yes
    with_items:
    - {'regexp': 'RPCNFSDARGS', 'line': 'RPCNFSDARGS="-N 2 -N 3"'}
    notify:
     - restart nfs
    when: ansible_distribution_major_version <=  "7"
    register: nfs_config7
      
  - name: Open Firewalld nfs port
    firewalld:
      service: nfs
      permanent: yes
      state: enabled
    ignore_errors: yes      

  - name: Open Firewalld nfs port
    firewalld:
      port: 892/tcp
      permanent: yes
      state: enabled
    ignore_errors: yes
