---
- name: Converge
  hosts: all
  become: true

  tasks:
    - file:
        path: /run/test
        state: directory

    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_mode: 'front'
        nfs_exports: [{path: "/run/test", export: "locahost(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"}]

    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_mode: 'wn'
